require("./javascripts/page_test.coffee")
require("./javascripts/turbolinks_test.coffee")
require("./javascripts/page_cache_test.coffee")
require("./javascripts/csrf_token_test.coffee")
require("./javascripts/component_url_test.coffee")
