# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 423f27429debeddb3dd1f1276fa5daf96e314e41872c1885851fe53bdd4f39480d5f38b47821f8281e32a19462fa867394baef662b6d12e055f3524907a1c1fe

test:
  secret_key_base: 81848b60d911250df442dea693156ae47a0229262018f541f14f473ed0597e0438aa102a9a94f0a9d7a63b1a3c332f94b66da9a13b8df1aebe03aec1e021d3ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
